version: "3.8"

services:
  parachain-node:
    container_name: parachain-node
    image: paritytech/ci-linux:production
    working_dir: /var/www/parachain-node
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/parachain-node/.cargo
    volumes:
      - .:/var/www/parachain-node
    command: bash -c "cargo build --release && ./target/release/all-in-network --dev --ws-external"
  rpc:
    container_name: rpc
    image: nginx:latest
    restart: unless-stopped
    environment:
      - DOMAIN
    depends_on:
      - parachain-node
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf/rpc/nginx/templates:/etc/nginx/templates:ro
      - ./conf/rpc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot/data:/var/www/certbot
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - rpc
    command: >-
              certonly --reinstall --webroot --webroot-path=/var/www/certbot
              --email ${EMAIL} --agree-tos --no-eff-email
              -d ${DOMAIN}
    volumes:
      - ./conf/rpc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot
