version: "3.8"

services:
  parachain-node:
    container_name: parachain-node
    image: paritytech/ci-linux:production
    working_dir: /var/www/parachain-node
    ports:
      - 9944:9944
    networks:
      - proxy
    environment:
      - CARGO_HOME=/var/www/parachain-node/.cargo
    volumes:
      - .:/var/www/parachain-node
    command: bash -c "cargo build --release && ./target/release/all-in-network --dev --ws-external"

networks:
  proxy:
    name: proxy
